# Generated by Django 5.2 on 2025-04-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=63)),
                ("slug", models.SlugField(max_length=63)),
                ("text", models.TextField()),
                ("pub_date", models.DateField()),
                ("startups", models.ManyToManyField(to="organizer.startup")),
                ("tags", models.ManyToManyField(to="organizer.tag")),
            ],
            options={
                "ordering": ["-pub_date", "title"],
                "get_latest_by": "pub_date",
            },
        ),
    ]
