# Generated by Django 5.2 on 2025-04-17 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=31, unique=True)),
                (
                    "slug",
                    models.SlugField(
                        help_text="A label for URL config.", max_length=31, unique=True
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Startup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=31)),
                (
                    "slug",
                    models.SlugField(
                        help_text="A label for URL config", max_length=31, unique=True
                    ),
                ),
                ("description", models.TextField()),
                ("founded_date", models.DateField(verbose_name="Date Founded")),
                ("contact", models.EmailField(max_length=254)),
                ("website", models.URLField()),
                ("tags", models.ManyToManyField(to="organizer.tag")),
            ],
            options={
                "ordering": ["name"],
                "get_latest_by": "founded_date",
            },
        ),
        migrations.CreateModel(
            name="NewsLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=31)),
                ("slug", models.SlugField(max_length=31)),
                ("pub_date", models.DateField()),
                ("link", models.URLField()),
                (
                    "startup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizer.startup",
                    ),
                ),
            ],
            options={
                "verbose_name": "news article",
                "ordering": ["-pub_date"],
                "get_latest_by": "pub_date",
                "unique_together": {("slug", "startup")},
            },
        ),
    ]
